"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import gitcommit as components_gitcommit
from ...models.components import httpmetadata as components_httpmetadata
from typing import Optional


@dataclasses.dataclass
class CreateCommitResponse:
    http_meta: components_httpmetadata.HTTPMetadata = dataclasses.field()
    git_commit: Optional[components_gitcommit.GitCommit] = dataclasses.field(default=None)
    r"""a list of GitCommitSummary objects"""
    

