"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import httpmetadata as components_httpmetadata
from ...models.components import notificationtargets as components_notificationtargets
from typing import Optional


@dataclasses.dataclass
class CreateNotificationTargetResponse:
    http_meta: components_httpmetadata.HTTPMetadata = dataclasses.field()
    notification_targets: Optional[components_notificationtargets.NotificationTargets] = dataclasses.field(default=None)
    r"""a list of NotificationTarget objects"""
    

