"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import httpmetadata as components_httpmetadata
from ...models.components import lookupfile as components_lookupfile
from typing import Optional, Union


@dataclasses.dataclass
class DeleteLookupRequest:
    id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'id', 'style': 'simple', 'explode': False }})
    r"""Unique ID"""
    



@dataclasses.dataclass
class DeleteLookupResponse:
    http_meta: components_httpmetadata.HTTPMetadata = dataclasses.field()
    lookup_file: Optional[Union[components_lookupfile.One, components_lookupfile.Two]] = dataclasses.field(default=None)
    r"""a list of LookupFile objects"""
    

