"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import authconfigs as components_authconfigs
from ...models.components import httpmetadata as components_httpmetadata
from typing import Optional


@dataclasses.dataclass
class GetAuthenticationSettingsResponse:
    http_meta: components_httpmetadata.HTTPMetadata = dataclasses.field()
    auth_configs: Optional[components_authconfigs.AuthConfigs] = dataclasses.field(default=None)
    r"""a list of AuthConfig objects"""
    

