"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import appscopelibentries as components_appscopelibentries
from ...models.components import httpmetadata as components_httpmetadata
from typing import Optional


@dataclasses.dataclass
class GetAppscopeLibEntriesResponse:
    http_meta: components_httpmetadata.HTTPMetadata = dataclasses.field()
    app_scope_lib_entries: Optional[components_appscopelibentries.AppScopeLibEntries] = dataclasses.field(default=None)
    r"""a list of AppscopeLibEntry objects"""
    

