"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import bulletinmessage as components_bulletinmessage
from ...models.components import httpmetadata as components_httpmetadata
from typing import Optional


@dataclasses.dataclass
class GetBulletinMessageRequest:
    id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'id', 'style': 'simple', 'explode': False }})
    r"""Unique ID"""
    



@dataclasses.dataclass
class GetBulletinMessageResponse:
    http_meta: components_httpmetadata.HTTPMetadata = dataclasses.field()
    bulletin_message: Optional[components_bulletinmessage.BulletinMessage] = dataclasses.field(default=None)
    r"""a list of BulletinMessage objects"""
    

