"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import branches as components_branches
from ...models.components import httpmetadata as components_httpmetadata
from typing import Optional


@dataclasses.dataclass
class GetBranchesResponse:
    http_meta: components_httpmetadata.HTTPMetadata = dataclasses.field()
    branches: Optional[components_branches.Branches] = dataclasses.field(default=None)
    r"""a list of any objects"""
    

