"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import httpmetadata as components_httpmetadata
from ...models.components import samplefiles as components_samplefiles
from typing import Optional


@dataclasses.dataclass
class GetBytesRequest:
    path: str = dataclasses.field(metadata={'query_param': { 'field_name': 'path', 'style': 'form', 'explode': True }})
    r"""The path to the file to sample"""
    bytes_requested: Optional[int] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'bytesRequested', 'style': 'form', 'explode': True }})
    r"""The number of bytes to return;   this value could be constrained by system limits."""
    



@dataclasses.dataclass
class GetBytesResponse:
    http_meta: components_httpmetadata.HTTPMetadata = dataclasses.field()
    sample_files: Optional[components_samplefiles.SampleFiles] = dataclasses.field(default=None)
    r"""a list of SampleFile objects"""
    

