"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import clientroleentries as shared_clientroleentries
from typing import Optional


@dataclasses.dataclass
class GetClientRolesResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    client_role_entries: Optional[shared_clientroleentries.ClientRoleEntries] = dataclasses.field(default=None)
    r"""a list of string objects"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    r"""Raw HTTP response; suitable for custom response parsing"""
    

