"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ...models.components import changedfiles as components_changedfiles
from typing import Optional


@dataclasses.dataclass
class GetChangedFilesRequest:
    group: Optional[str] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'group', 'style': 'form', 'explode': True }})
    r"""Group ID"""
    id: Optional[str] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'ID', 'style': 'form', 'explode': True }})
    r"""Commit ID"""
    



@dataclasses.dataclass
class GetChangedFilesResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    changed_files: Optional[components_changedfiles.ChangedFiles] = dataclasses.field(default=None)
    r"""a list of GitFilesResponse objects"""
    

