"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import fieldsummaries as shared_fieldsummaries
from typing import Optional



@dataclasses.dataclass
class GetFieldSummariesRequest:
    id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'id', 'style': 'simple', 'explode': False }})
    r"""search job id"""
    




@dataclasses.dataclass
class GetFieldSummariesResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    field_summaries: Optional[shared_fieldsummaries.FieldSummaries] = dataclasses.field(default=None)
    r"""FieldSummaries object"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    

