"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import globalvars as shared_globalvars
from typing import Optional



@dataclasses.dataclass
class GetGlobalVariableIDRequest:
    id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'id', 'style': 'simple', 'explode': False }})
    r"""Unique ID"""
    




@dataclasses.dataclass
class GetGlobalVariableIDResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    global_vars: Optional[shared_globalvars.GlobalVars] = dataclasses.field(default=None)
    r"""a list of Global Variable objects"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    

