"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import httpmetadata as components_httpmetadata
from ...models.components import searchjobstatus as components_searchjobstatus
from typing import Optional


@dataclasses.dataclass
class GetJobStatusRequest:
    id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'id', 'style': 'simple', 'explode': False }})
    r"""search job id"""
    



@dataclasses.dataclass
class GetJobStatusResponse:
    http_meta: components_httpmetadata.HTTPMetadata = dataclasses.field()
    search_job_status: Optional[components_searchjobstatus.SearchJobStatus] = dataclasses.field(default=None)
    r"""SearchJobStatus object"""
    

