"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import httpmetadata as components_httpmetadata
from ...models.components import loggerconfigs as components_loggerconfigs
from typing import Optional


@dataclasses.dataclass
class GetLoggerConfigsResponse:
    http_meta: components_httpmetadata.HTTPMetadata = dataclasses.field()
    logger_configs: Optional[components_loggerconfigs.LoggerConfigs] = dataclasses.field(default=None)
    r"""a list of LoggerConfig objects"""
    

