"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import loggerconfigs as shared_loggerconfigs
from typing import Optional



@dataclasses.dataclass
class GetLoggerConfigsResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    logger_configs: Optional[shared_loggerconfigs.LoggerConfigs] = dataclasses.field(default=None)
    r"""a list of LoggerConfig objects"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    

