"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import dailymetrics as shared_dailymetrics
from typing import Optional



@dataclasses.dataclass
class GetLicenseUsageMetricsResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    daily_metrics: Optional[shared_dailymetrics.DailyMetrics] = dataclasses.field(default=None)
    r"""a list of DailyUsageMetrics objects"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    

