"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import httpmetadata as components_httpmetadata
from ...models.components import profileritem as components_profileritem
from typing import Optional


@dataclasses.dataclass
class GetProfilerRequest:
    id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'id', 'style': 'simple', 'explode': False }})
    r"""Unique ID"""
    



@dataclasses.dataclass
class GetProfilerResponse:
    http_meta: components_httpmetadata.HTTPMetadata = dataclasses.field()
    profiler_item: Optional[components_profileritem.ProfilerItem] = dataclasses.field(default=None)
    r"""a list of ProfilerItem objects"""
    

