"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import parserlibentries as shared_parserlibentries
from typing import Optional



@dataclasses.dataclass
class GetParserIDRequest:
    id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'id', 'style': 'simple', 'explode': False }})
    r"""Unique ID"""
    




@dataclasses.dataclass
class GetParserIDResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    parser_lib_entries: Optional[shared_parserlibentries.ParserLibEntries] = dataclasses.field(default=None)
    r"""a list of Parser objects"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    

