"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import httpmetadata as components_httpmetadata
from ...models.components import routes as components_routes
from typing import Optional


@dataclasses.dataclass
class GetRouteListIDRequest:
    id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'id', 'style': 'simple', 'explode': False }})
    r"""There is only one route entity and it should be accessed with id: default."""
    



@dataclasses.dataclass
class GetRouteListIDResponse:
    http_meta: components_httpmetadata.HTTPMetadata = dataclasses.field()
    routes: Optional[components_routes.Routes] = dataclasses.field(default=None)
    r"""a list of Routes objects"""
    

