"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import httpmetadata as components_httpmetadata
from ...models.components import redirectinfo as components_redirectinfo
from typing import Optional


@dataclasses.dataclass
class GetRedirectInfoResponse:
    http_meta: components_httpmetadata.HTTPMetadata = dataclasses.field()
    redirect_info: Optional[components_redirectinfo.RedirectInfo] = dataclasses.field(default=None)
    r"""Redirect info"""
    

