"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import httpmetadata as components_httpmetadata
from ...models.errors import success as errors_success
from typing import Optional


@dataclasses.dataclass
class GetRequestAuthRequest:
    relay_state: Optional[str] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'RelayState', 'style': 'form', 'explode': True }})
    saml_response: Optional[str] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'SAMLResponse', 'style': 'form', 'explode': True }})
    r"""Authentication request object"""
    



@dataclasses.dataclass
class GetRequestAuthResponse:
    http_meta: components_httpmetadata.HTTPMetadata = dataclasses.field()
    success: Optional[errors_success.Success] = dataclasses.field(default=None)
    r"""Authentication success"""
    

