"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import httpmetadata as components_httpmetadata
from ...models.components import savedjobs as components_savedjobs
from typing import Optional


@dataclasses.dataclass
class GetSavedJobRequest:
    id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'id', 'style': 'simple', 'explode': False }})
    r"""Unique ID"""
    



@dataclasses.dataclass
class GetSavedJobResponse:
    http_meta: components_httpmetadata.HTTPMetadata = dataclasses.field()
    saved_jobs: Optional[components_savedjobs.SavedJobs] = dataclasses.field(default=None)
    r"""a list of SavedJob objects"""
    

