"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import httpmetadata as components_httpmetadata
from ...models.components import searchlogs as components_searchlogs
from typing import Optional


@dataclasses.dataclass
class GetSearchLogsRequest:
    id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'id', 'style': 'simple', 'explode': False }})
    r"""search job id"""
    



@dataclasses.dataclass
class GetSearchLogsResponse:
    http_meta: components_httpmetadata.HTTPMetadata = dataclasses.field()
    search_logs: Optional[components_searchlogs.SearchLogs] = dataclasses.field(default=None)
    r"""a list of string objects"""
    

