"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import httpmetadata as components_httpmetadata
from ...models.components import savedqueries as components_savedqueries
from typing import Optional


@dataclasses.dataclass
class GetSavedQueriesResponse:
    http_meta: components_httpmetadata.HTTPMetadata = dataclasses.field()
    saved_queries: Optional[components_savedqueries.SavedQueries] = dataclasses.field(default=None)
    r"""a list of SavedQuery objects"""
    

