"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import systeminfoobjects as shared_systeminfoobjects
from typing import Optional



@dataclasses.dataclass
class GetSystemInfoResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    system_info_objects: Optional[shared_systeminfoobjects.SystemInfoObjects] = dataclasses.field(default=None)
    r"""a list of SystemInfo objects"""
    

