"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import trustpolicies as shared_trustpolicies
from typing import Optional



@dataclasses.dataclass
class GetTrustPoliciesResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    trust_policies: Optional[shared_trustpolicies.TrustPolicies] = dataclasses.field(default=None)
    r"""a list of TrustPolicy objects"""
    

