"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import gitinfos as components_gitinfos
from ...models.components import httpmetadata as components_httpmetadata
from typing import Optional


@dataclasses.dataclass
class GetVersioningResponse:
    http_meta: components_httpmetadata.HTTPMetadata = dataclasses.field()
    git_infos: Optional[components_gitinfos.GitInfos] = dataclasses.field(default=None)
    r"""a list of GitInfo objects"""
    

