"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import gitstatusresults as components_gitstatusresults
from ...models.components import httpmetadata as components_httpmetadata
from typing import Optional


@dataclasses.dataclass
class GetWorkingTreeRequest:
    group: Optional[str] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'group', 'style': 'form', 'explode': True }})
    r"""Group ID"""
    



@dataclasses.dataclass
class GetWorkingTreeResponse:
    http_meta: components_httpmetadata.HTTPMetadata = dataclasses.field()
    git_status_results: Optional[components_gitstatusresults.GitStatusResults] = dataclasses.field(default=None)
    r"""a list of GitStatusResult objects"""
    

