"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import authtoken as shared_authtoken
from typing import Optional



@dataclasses.dataclass
class LoginAuthTokenResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    auth_token: Optional[shared_authtoken.AuthToken] = dataclasses.field(default=None)
    r"""Authentication token"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    

