"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import httpmetadata as components_httpmetadata
from ...models.components import jobpause as components_jobpause
from typing import Optional


@dataclasses.dataclass
class PauseJobRequest:
    id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'id', 'style': 'simple', 'explode': False }})
    r"""Job instance id"""
    



@dataclasses.dataclass
class PauseJobResponse:
    http_meta: components_httpmetadata.HTTPMetadata = dataclasses.field()
    job_pause: Optional[components_jobpause.JobPause] = dataclasses.field(default=None)
    r"""a list of any objects"""
    

