"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ...models.components import metricsinfo as components_metricsinfo
from typing import Optional


@dataclasses.dataclass
class PostMetricsResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    metrics_info: Optional[components_metricsinfo.MetricsInfo] = dataclasses.field(default=None)
    r"""a list of MetricNameInfo objects"""
    

