"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import httpmetadata as components_httpmetadata
from ...models.components import parserlibentries as components_parserlibentries
from typing import Optional


@dataclasses.dataclass
class PostParserObjectResponse:
    http_meta: components_httpmetadata.HTTPMetadata = dataclasses.field()
    parser_lib_entries: Optional[components_parserlibentries.ParserLibEntries] = dataclasses.field(default=None)
    r"""a list of Parser objects"""
    

