"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import databaseconnectiontestresults as components_databaseconnectiontestresults
from ...models.components import httpmetadata as components_httpmetadata
from typing import Optional


@dataclasses.dataclass
class PostTestDatabaseConnectionResponse:
    http_meta: components_httpmetadata.HTTPMetadata = dataclasses.field()
    database_connection_test_results: Optional[components_databaseconnectiontestresults.DatabaseConnectionTestResults] = dataclasses.field(default=None)
    r"""a list of DatabaseConnectionTestResult objects"""
    

