"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ...models.components import criblpackage as components_criblpackage
from typing import Optional


@dataclasses.dataclass
class PostStageDistributedPackageRequest:
    group: str = dataclasses.field(metadata={'path_param': { 'field_name': 'group', 'style': 'simple', 'explode': False }})
    r"""Group to upgrade"""
    upgrade_percentage: Optional[str] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'upgradePercentage', 'style': 'form', 'explode': True }})
    r"""body number percentage of nodes on the worker group to upgrade"""
    



@dataclasses.dataclass
class PostStageDistributedPackageResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    cribl_package: Optional[components_criblpackage.CriblPackage] = dataclasses.field(default=None)
    r"""a list of any objects"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    r"""Raw HTTP response; suitable for custom response parsing"""
    

