"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import pushconfig as shared_pushconfig
from typing import Optional



@dataclasses.dataclass
class PushCurrentConfigResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    push_config: Optional[shared_pushconfig.PushConfig] = dataclasses.field(default=None)
    r"""a list of any objects"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    

