"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import jobrun as shared_jobrun
from typing import Optional



@dataclasses.dataclass
class RunJobResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    job_run: Optional[shared_jobrun.JobRun] = dataclasses.field(default=None)
    r"""a list of string objects"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    

