"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import httpmetadata as components_httpmetadata
from ...models.components import jobrun as components_jobrun
from typing import Optional


@dataclasses.dataclass
class RunJobResponse:
    http_meta: components_httpmetadata.HTTPMetadata = dataclasses.field()
    job_run: Optional[components_jobrun.JobRun] = dataclasses.field(default=None)
    r"""a list of string objects"""
    

