"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import savedjobs as shared_savedjobs
from typing import Any, Optional



@dataclasses.dataclass
class UpdateSavedJobRequest:
    id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'id', 'style': 'simple', 'explode': False }})
    r"""Unique ID"""
    request_body: Optional[Any] = dataclasses.field(default=None, metadata={'request': { 'media_type': 'application/json' }})
    r"""SavedJob object to be updated"""
    




@dataclasses.dataclass
class UpdateSavedJobResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    saved_jobs: Optional[shared_savedjobs.SavedJobs] = dataclasses.field(default=None)
    r"""a list of SavedJob objects"""
    

