"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import httpmetadata as components_httpmetadata
from ...models.components import uistatepatch as components_uistatepatch
from ...models.components import uistates as components_uistates
from typing import Optional


@dataclasses.dataclass
class UpdateUIStateRequest:
    key: str = dataclasses.field(metadata={'path_param': { 'field_name': 'key', 'style': 'simple', 'explode': False }})
    r"""UI state key"""
    ui_state_patch: Optional[components_uistatepatch.UIStatePatch] = dataclasses.field(default=None, metadata={'request': { 'media_type': 'application/json' }})
    r"""UI State Patch object"""
    



@dataclasses.dataclass
class UpdateUIStateResponse:
    http_meta: components_httpmetadata.HTTPMetadata = dataclasses.field()
    ui_states: Optional[components_uistates.UIStates] = dataclasses.field(default=None)
    r"""a list of any objects"""
    

