"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import httpmetadata as components_httpmetadata
from ...models.components import policyrule as components_policyrule
from ...models.components import policyrules as components_policyrules
from typing import Optional


@dataclasses.dataclass
class UpdatePolicyRuleRequest:
    id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'id', 'style': 'simple', 'explode': False }})
    r"""Unique ID"""
    policy_rule: Optional[components_policyrule.PolicyRule] = dataclasses.field(default=None, metadata={'request': { 'media_type': 'application/json' }})
    r"""PolicyRule object to be updated"""
    



@dataclasses.dataclass
class UpdatePolicyRuleResponse:
    http_meta: components_httpmetadata.HTTPMetadata = dataclasses.field()
    policy_rules: Optional[components_policyrules.PolicyRules] = dataclasses.field(default=None)
    r"""a list of PolicyRule objects"""
    

