"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import profileritem as shared_profileritem
from typing import Optional



@dataclasses.dataclass
class UpdateProfilerRequest:
    id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'id', 'style': 'simple', 'explode': False }})
    r"""Unique ID"""
    profiler_item: Optional[shared_profileritem.ProfilerItem] = dataclasses.field(default=None, metadata={'request': { 'media_type': 'application/json' }})
    r"""ProfilerItem object to be updated"""
    




@dataclasses.dataclass
class UpdateProfilerResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    profiler_item: Optional[shared_profileritem.ProfilerItem] = dataclasses.field(default=None)
    r"""a list of ProfilerItem objects"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    

