"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import httpmetadata as components_httpmetadata
from typing import Any, Optional


@dataclasses.dataclass
class UpdateDatasetObjectRequest:
    id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'id', 'style': 'simple', 'explode': False }})
    r"""Unique ID"""
    request_body: Optional[Any] = dataclasses.field(default=None, metadata={'request': { 'media_type': 'application/json' }})
    r"""Dataset object to be updated"""
    



@dataclasses.dataclass
class UpdateDatasetObjectResponse:
    http_meta: components_httpmetadata.HTTPMetadata = dataclasses.field()
    dataset: Optional[Any] = dataclasses.field(default=None)
    r"""a list of Dataset objects"""
    

