"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import httpmetadata as components_httpmetadata
from ...models.components import packinfos as components_packinfos
from typing import Optional


@dataclasses.dataclass
class UpgradePackRequest:
    id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'id', 'style': 'simple', 'explode': False }})
    r"""Pack name"""
    minor: Optional[str] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'minor', 'style': 'form', 'explode': True }})
    r"""body boolean optional Only upgrade to minor/patch versions"""
    source: Optional[str] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'source', 'style': 'form', 'explode': True }})
    r"""body string required Pack source"""
    spec: Optional[str] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'spec', 'style': 'form', 'explode': True }})
    r"""body string optional Specify a branch, tag or a semver spec"""
    



@dataclasses.dataclass
class UpgradePackResponse:
    http_meta: components_httpmetadata.HTTPMetadata = dataclasses.field()
    pack_infos: Optional[components_packinfos.PackInfos] = dataclasses.field(default=None)
    r"""a list of PackInfo objects"""
    

