"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ...models.components import lookupfileinforesponse as components_lookupfileinforesponse
from typing import Optional


@dataclasses.dataclass
class UploadLookupRequest:
    filename: Optional[str] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'filename', 'style': 'form', 'explode': True }})
    r"""query LookupFilenameSchema required Filename"""
    



@dataclasses.dataclass
class UploadLookupResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    lookup_file_info_response: Optional[components_lookupfileinforesponse.LookupFileInfoResponse] = dataclasses.field(default=None)
    r"""LookupFileInfoResponse object"""
    

