"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class FieldType(str, Enum):
    ARRAY = 'array'
    BOOLEAN = 'boolean'
    NUMBER = 'number'
    OBJECT = 'object'
    STRING = 'string'
    TIMESTAMP = 'timestamp'
