"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class SecretProvider(str, Enum):
    LOCAL = 'local'
    VAULT = 'vault'
    AWS_KMS = 'aws-kms'
